index:
    path: /
    controller: App\Controller\MainController::index

app_task:
    path: /register
    controller: App\Controller\RegisterController::registerAction

app_done:
    path: /login
    controller: App\Controller\SecutiyController::login

app_admin:
    path: /admin
    controller: App\Controller\AdminController::admin
app_adminEdit:
        path: /admin-edit
        controller: App\Controller\AdminEditController::adminEdit
app_list:
    path: /list
    controller: App\Controller\ListController::list
app_masterList:
    path: /master
    controller: App\Controller\MasterListController::masterList
app_masterCreate:
    path: /master-create
    controller: App\Controller\MasterListCreateController::MasterCreate
app_masterEdit:
    path: /master-edit
    controller: App\Controller\MasterListEditController::MasterEdit
app_masterDelete:
    path: /master-delete
    controller: App\Controller\MasterListDeleteController::MasterDelete
app_listCreate:
    path: /list-create
    controller: App\Controller\ListCreateController::listCreate
app_listEdit:
    path: /list-edit
    controller: App\Controller\ListEditController::listEdit
app_listDelete:
    path: /list-delete
    controller: App\Controller\ListDeleteController::listDelete
logout:
    path: /logout