index:
    path: /
    controller: App\Controller\MainController::index

app_task:
    path: /register
    controller: App\Controller\RegisterController::registerAction

app_done:
    path: /login
    controller: App\Controller\SecutiyController::login

app_admin:
    path: /admin
    controller: App\Controller\AdminController::admin