<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIwTNRYh\srcDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIwTNRYh/srcDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIwTNRYh.legacy');

    return;
}

if (!\class_exists(srcDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIwTNRYh\srcDebugProjectContainer::class, srcDebugProjectContainer::class, false);
}

return new \ContainerIwTNRYh\srcDebugProjectContainer(array(
    'container.build_hash' => 'IwTNRYh',
    'container.build_id' => 'd9d49f56',
    'container.build_time' => 1516888829,
));
