<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVFqAZqj\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVFqAZqj/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVFqAZqj.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVFqAZqj\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVFqAZqj\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'VFqAZqj',
    'container.build_id' => '136dcbda',
    'container.build_time' => 1517339556,
));
