<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJZTiR8x\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJZTiR8x/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJZTiR8x.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJZTiR8x\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJZTiR8x\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JZTiR8x',
    'container.build_id' => 'c9a0727c',
    'container.build_time' => 1517832589,
));
