<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3HljI6D\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3HljI6D/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3HljI6D.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3HljI6D\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container3HljI6D\srcDevDebugProjectContainer(array(
    'container.build_hash' => '3HljI6D',
    'container.build_id' => 'ff19a85a',
    'container.build_time' => 1515696536,
));
